# Generated by Django 4.1 on 2025-02-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignparticipation',
            name='user_id',
        ),
    ]
