# Generated by Django 4.1 on 2025-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
