# Generated by Django 4.2 on 2025-03-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
